### ISSUE TITLE
Use acsiimath

### ISSUE THREAD

**Issue by Kerl13** [Phyks/pandoc_boilerplate#10]
Hi,

Most problems you have mentioned would be solved by using my implementation of [asciimath](https://github.com/Kerl13/AsciiMath). It is a far better solution than what i proposed for #2 #4 and it is also related to issue #3 about delimiters.

Are you interested ?

**Comment by Phyks** [comment]
Sure, was the plan :)

**Comment by Kerl13** [comment]
So take a look at #11  ;)
